### ISSUE TITLE
um bom bot

### ISSUE THREAD

**Issue by victalejo** [metheuspsc/Iq_Option_Bots#1]
Eu amo o seu bot, ele tem uma lucratividade incrível, mas às vezes começa a perder muito, você precisa levar em consideração as horas? Em caso afirmativo, você poderia me indicar ... Muito obrigado, excelente trabalho, onde posso doar para você?

**Comment by metheuspsc** [comment]
Olá @victalejo , qual bot você está usando? No caso do MHI_Potencializado ele só replica a estratégia sem fazer análises mais profundas, de tendência e etc. Pretendo criar mais bots baseados nas estrátégias comuns e também um catalogador no futuro, pra medir qual estratégia performa melhor no gráfico atual. Aceito doações através do picpay @matheus.pessoa

**Comment by victalejo** [comment]
Estou usando Bot_80% porque o MHI_Potentialized não funciona para mim, eu o tenho aberto, mas não haverá operações. Eu sou da Colômbia, o picpay não funciona aqui.

**Comment by metheuspsc** [comment]
Qual o nível de acerto que vc tem obtido com o Bot 80%, tenho trabalhado bastante nele esses dias pra reduzir os erros, ele realiza 5 ordens antes de atualizar o modelo de previsão, então tem espaço pro mercado mudar completamente. Uma solução foi validar a primeira previsão antes de realizar a ordem. Também tenho o paypal matheuspessoax@gmail.com

**Comment by victalejo** [comment]
Às vezes é 80-100%, mas outras vezes 30-50% não sei quando o bem será

**Comment by victalejo** [comment]
Model_JBS.py também não funciona para mim, ele diz que há uma variável mal definida

**Comment by metheuspsc** [comment]
O Model_JBS ainda está em desenvolvimento, é um projeto pra aplicar o modelo em ações brasileiras. Ainda estou vendo como reduzir a instabilidade no bot 80% ele deve estar errando pela falta de algum indicador no modelo.
