### ISSUE TITLE
TypeError: cannot unpack non-iterable int object

### ISSUE THREAD

**Issue by BernardoCR** [metheuspsc/Iq_Option_Bots#3]
Estou recebendo esse erro, o robô chega a executar a entrada, mas acontece esse erro logo em seguida. no Bot_80%.py.

```
Traceback (most recent call last):
  File "Bot_80%.py", line 175, in <module>
    par, valor_entrada, bs, 1)
TypeError: cannot unpack non-iterable int object
```

**Comment by metheuspsc** [comment]
Provavelmente o valor que você está passando para a entrada não é um Int
