### ISSUE TITLE
Fica apenas em "Próximo Sinal"

### ISSUE THREAD

**Issue by gabcarvalhogama** [metheuspsc/Iq_Option_Bots#4]
Boa tarde, tudo certo, amigo?

Coloquei o bot de 80% para rodar, porém ele só fica retornando Próximo Sinal, infinitamente. O que acha que pode ser?

**Comment by gabcarvalhogama** [comment]
![image](https://user-images.githubusercontent.com/8550468/90340453-a56f1900-dfce-11ea-8e97-2f7a435dfd0b.png)

**Comment by gabcarvalhogama** [comment]
E quando dou print() em results, retorna:

![image](https://user-images.githubusercontent.com/8550468/90340765-e36d3c80-dfd0-11ea-86db-f344beb63008.png)

**Comment by metheuspsc** [comment]
Fala Gabriel, no caso, tem algum erro com a Data do seu data frame, repare q ela tá como '1970-01-04'

**Comment by gabcarvalhogama** [comment]
Caramba, entendi! Imaginei que o problema estivesse realmente nessa questão do parse da Data. Porém, sou leigo em Python. Como você sugere que eu resolva isso, amigo?
